// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACXjy4MM7pnCOXN-7chFBR3qVnDUsxQ1s',
    appId: '1:502046453928:web:c8cffc18c15c09671e529d',
    messagingSenderId: '502046453928',
    projectId: 'fyp1-da867',
    authDomain: 'fyp1-da867.firebaseapp.com',
    storageBucket: 'fyp1-da867.firebasestorage.app',
    measurementId: 'G-Y45MSXEXJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYQRraMa55NtPHFNQpeAvc0YsCks4imTg',
    appId: '1:502046453928:android:97549b2344440cee1e529d',
    messagingSenderId: '502046453928',
    projectId: 'fyp1-da867',
    storageBucket: 'fyp1-da867.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQYVpheEUfYC4MdgD7V2Q1aBVx7mCTWk0',
    appId: '1:502046453928:ios:d58ce348ad1f6cc11e529d',
    messagingSenderId: '502046453928',
    projectId: 'fyp1-da867',
    storageBucket: 'fyp1-da867.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQYVpheEUfYC4MdgD7V2Q1aBVx7mCTWk0',
    appId: '1:502046453928:ios:d58ce348ad1f6cc11e529d',
    messagingSenderId: '502046453928',
    projectId: 'fyp1-da867',
    storageBucket: 'fyp1-da867.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACXjy4MM7pnCOXN-7chFBR3qVnDUsxQ1s',
    appId: '1:502046453928:web:43d75f174c995bcd1e529d',
    messagingSenderId: '502046453928',
    projectId: 'fyp1-da867',
    authDomain: 'fyp1-da867.firebaseapp.com',
    storageBucket: 'fyp1-da867.firebasestorage.app',
    measurementId: 'G-6RP42T50S4',
  );
}
